###########
# Aliases #
###########
#alias open='nautilus'
alias open='thunar'
alias mc='mc -x' # Open midnight commander with xterm support (allows mouse click events from within tmux)
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias wmip='curl ifconfig.co'
alias wimip='curl ifconfig.co'
alias exe='chmod +x'
alias inst='sudo apt install'
alias ipa='ip -brief address'
alias ipl='ip -brief link'
alias pbcopy="xclip -selection clipboard"
alias sshrm='ssh-keygen -R' # Alias to remove ssh keys
alias pyweb='python -m SimpleHTTPServer' # Quick and simple webserver
alias pping='prettyping --nolegend'
alias now='date +%Y.%m.%d_%H.%M.%S'
alias now-e='date +%s'
alias gs='git status'
alias h='history'
alias ports='netstat -tulanp'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
